### ISSUE TITLE
Unterpunkt: Audio

### ISSUE THREAD

**Issue by fredericaudio** [disktree/stritter.audio#1]
Allgemein: 
Können wir hier Fotos mit hinzufühgen? Kann der Player nur als Pop Up funktionieren?

Einzeln:
Das Soundfile bei Einsiedlerpark ist das Flasche. 
Die Beschreibungen (mikrofone etc. stimmen teils nicht)

**Comment by tong** [comment]
Player kann man machen, ist aber nicht wenig arbeit.
Vielleicht mit einer implementation für velak umsetzen.

Die sound files liegen hier https://github.com/disktree/stritter.audio/tree/master/assets/audio. Am besten einfach direkt auf github raufladen.

Die beschreibungen auch am besten direkt auf github ändern.
zb: https://github.com/disktree/stritter.audio/blob/master/content/audio/einsiedlerpark.md
