### ISSUE TITLE
Host font files

### ISSUE THREAD

**Issue by tong** [disktree/stritter.audio#10]
Do not use fonts.google for hosting font files.  
Find a way to convert ttf to woff2 without breaking the Inter font family (on macos).

~Try: https://cloudconvert.com/ttf-to-woff2~ (same issue).

See https://github.com/verein-fuer-elektro-akustik/velak.klingt.org/issues/5

**Comment by tong** [comment]
Should be fixed: https://disktree.github.io/stritter.audio/
@Kilmou ?

**Comment by Kilmou** [comment]
Yes, seems fixed!
