### ISSUE TITLE
Credits für Fotos + Videos

### ISSUE THREAD

**Issue by fredericaudio** [disktree/stritter.audio#5]

**Comment by tong** [comment]
Bei den project content files gibts ein `photos` feld wo man den namen des fotographen eintragen kann.
Das sollte dann unter den bildern angezeigt werden.

zb: https://github.com/disktree/stritter.audio/blob/master/content/project/a_certain_trio/index.md

**Comment by tong** [comment]
Sag mir die namen der photographen dann trag ichs ein.
